// Author: Paul Snow
// Tests for the RipLibraryRepositoryImpl mapping layer.
//
// These tests isolate the repository from the database by mocking
// RipLibraryDao.  The focus is on verifying that:
//   • Drift data-class rows are faithfully mapped to domain entities.
//   • Write operations build the correct companions and delegate to the DAO.
//   • Simple delegation methods forward their arguments unchanged.

import 'package:drift/drift.dart' hide isNull, isNotNull;
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';
import 'package:mymediascanner/data/local/dao/rip_library_dao.dart';
import 'package:mymediascanner/data/local/database/app_database.dart';
import 'package:mymediascanner/data/repositories/rip_library_repository_impl.dart';
import 'package:mymediascanner/domain/entities/rip_album.dart';
import 'package:mymediascanner/domain/entities/rip_track.dart';

// ---------------------------------------------------------------------------
// Mock
// ---------------------------------------------------------------------------

class MockRipLibraryDao extends Mock implements RipLibraryDao {}

// ---------------------------------------------------------------------------
// Helpers – construct Drift data-class instances directly.
// These are plain const-constructible value objects generated by Drift.
// ---------------------------------------------------------------------------

RipAlbumsTableData _makeAlbumRow({
  String id = 'rip-1',
  String libraryPath = 'Artist/Album',
  String? artist = 'Test Artist',
  String? albumTitle = 'Test Album',
  String? barcode = '5099902894225',
  int trackCount = 10,
  int discCount = 1,
  int totalSizeBytes = 500000000,
  String? mediaItemId,
  int lastScannedAt = 1700000000000,
  int updatedAt = 1700000001000,
  int deleted = 0,
}) =>
    RipAlbumsTableData(
      id: id,
      libraryPath: libraryPath,
      artist: artist,
      albumTitle: albumTitle,
      barcode: barcode,
      trackCount: trackCount,
      discCount: discCount,
      totalSizeBytes: totalSizeBytes,
      mediaItemId: mediaItemId,
      lastScannedAt: lastScannedAt,
      updatedAt: updatedAt,
      deleted: deleted,
    );

RipTracksTableData _makeTrackRow({
  String id = 'track-1',
  String ripAlbumId = 'rip-1',
  int discNumber = 1,
  int trackNumber = 1,
  String? title = 'Track One',
  String filePath = '/music/track1.flac',
  int? durationMs = 240000,
  int fileSizeBytes = 50000000,
  int updatedAt = 1700000001000,
  String? accurateripStatus,
  int? accurateripConfidence,
  String? accurateripCrc,
  double? peakLevel,
  double? trackQuality,
  String? copyCrc,
  int? clickCount,
  String? ripLogSource,
  int? qualityCheckedAt,
}) =>
    RipTracksTableData(
      id: id,
      ripAlbumId: ripAlbumId,
      discNumber: discNumber,
      trackNumber: trackNumber,
      title: title,
      filePath: filePath,
      durationMs: durationMs,
      fileSizeBytes: fileSizeBytes,
      updatedAt: updatedAt,
      accurateripStatus: accurateripStatus,
      accurateripConfidence: accurateripConfidence,
      accurateripCrc: accurateripCrc,
      peakLevel: peakLevel,
      trackQuality: trackQuality,
      copyCrc: copyCrc,
      clickCount: clickCount,
      ripLogSource: ripLogSource,
      qualityCheckedAt: qualityCheckedAt,
    );

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

void main() {
  late MockRipLibraryDao mockDao;
  late RipLibraryRepositoryImpl repository;

  setUp(() {
    mockDao = MockRipLibraryDao();
    repository = RipLibraryRepositoryImpl(ripLibraryDao: mockDao);
  });

  // Register fallback values for companion types used in verify() capture.
  setUpAll(() {
    registerFallbackValue(RipAlbumsTableCompanion(
      id: const Value(''),
      libraryPath: const Value(''),
      trackCount: const Value(0),
      discCount: const Value(1),
      totalSizeBytes: const Value(0),
      lastScannedAt: const Value(0),
      updatedAt: const Value(0),
    ));
    registerFallbackValue(<RipTracksTableCompanion>[]);
  });

  // -------------------------------------------------------------------------
  group('watchAll', () {
    test(
      'watchAll_withAlbumRows_mapsToRipAlbumEntities',
      () async {
        final row = _makeAlbumRow(mediaItemId: 'item-1');
        when(() => mockDao.watchAll())
            .thenAnswer((_) => Stream.value([row]));

        final albums = await repository.watchAll().first;

        expect(albums, hasLength(1));
        final album = albums.first;
        expect(album.id, 'rip-1');
        expect(album.libraryPath, 'Artist/Album');
        expect(album.artist, 'Test Artist');
        expect(album.albumTitle, 'Test Album');
        expect(album.barcode, '5099902894225');
        expect(album.trackCount, 10);
        expect(album.discCount, 1);
        expect(album.totalSizeBytes, 500000000);
        expect(album.mediaItemId, 'item-1');
        expect(album.lastScannedAt, 1700000000000);
        expect(album.updatedAt, 1700000001000);
        expect(album.deleted, isFalse);
      },
    );

    test(
      'watchAll_withDeletedRow_mapsDeletedFlagToTrue',
      () async {
        final row = _makeAlbumRow(deleted: 1);
        when(() => mockDao.watchAll())
            .thenAnswer((_) => Stream.value([row]));

        final albums = await repository.watchAll().first;

        expect(albums.first.deleted, isTrue);
      },
    );

    test(
      'watchAll_withEmptyStream_emitsEmptyList',
      () async {
        when(() => mockDao.watchAll())
            .thenAnswer((_) => Stream.value([]));

        final albums = await repository.watchAll().first;

        expect(albums, isEmpty);
      },
    );
  });

  // -------------------------------------------------------------------------
  group('getAllNonDeleted', () {
    test(
      'getAllNonDeleted_withRows_returnsListOfRipAlbumEntities',
      () async {
        final rows = [
          _makeAlbumRow(id: 'rip-1'),
          _makeAlbumRow(id: 'rip-2', artist: 'Other Artist'),
        ];
        when(() => mockDao.getAllNonDeleted())
            .thenAnswer((_) async => rows);

        final albums = await repository.getAllNonDeleted();

        expect(albums, hasLength(2));
        expect(albums[0].id, 'rip-1');
        expect(albums[1].id, 'rip-2');
        expect(albums[1].artist, 'Other Artist');
      },
    );

    test(
      'getAllNonDeleted_withNoRows_returnsEmptyList',
      () async {
        when(() => mockDao.getAllNonDeleted()).thenAnswer((_) async => []);

        final albums = await repository.getAllNonDeleted();

        expect(albums, isEmpty);
      },
    );
  });

  // -------------------------------------------------------------------------
  group('getTracksForAlbum', () {
    test(
      'getTracksForAlbum_withQualityFields_mapsAllQualityFieldsToEntity',
      () async {
        final row = _makeTrackRow(
          id: 'track-1',
          ripAlbumId: 'rip-1',
          discNumber: 2,
          trackNumber: 5,
          title: 'Quality Track',
          filePath: '/music/quality.flac',
          durationMs: 300000,
          fileSizeBytes: 60000000,
          updatedAt: 1700000002000,
          accurateripStatus: 'verified',
          accurateripConfidence: 42,
          accurateripCrc: 'ABCD1234',
          peakLevel: -0.5,
          trackQuality: 98.7,
          copyCrc: 'EFGH5678',
          clickCount: 3,
          ripLogSource: 'EAC',
          qualityCheckedAt: 1700000003000,
        );
        when(() => mockDao.getTracksForAlbum('rip-1'))
            .thenAnswer((_) async => [row]);

        final tracks = await repository.getTracksForAlbum('rip-1');

        expect(tracks, hasLength(1));
        final track = tracks.first;
        expect(track.id, 'track-1');
        expect(track.ripAlbumId, 'rip-1');
        expect(track.discNumber, 2);
        expect(track.trackNumber, 5);
        expect(track.title, 'Quality Track');
        expect(track.filePath, '/music/quality.flac');
        expect(track.durationMs, 300000);
        expect(track.fileSizeBytes, 60000000);
        expect(track.updatedAt, 1700000002000);
        expect(track.accurateRipStatus, 'verified');
        expect(track.accurateRipConfidence, 42);
        expect(track.accurateRipCrc, 'ABCD1234');
        expect(track.peakLevel, -0.5);
        expect(track.trackQuality, 98.7);
        expect(track.copyCrc, 'EFGH5678');
        expect(track.clickCount, 3);
        expect(track.ripLogSource, 'EAC');
        expect(track.qualityCheckedAt, 1700000003000);
      },
    );

    test(
      'getTracksForAlbum_withNullQualityFields_producesEntityWithNulls',
      () async {
        final row = _makeTrackRow(
          accurateripStatus: null,
          accurateripConfidence: null,
          accurateripCrc: null,
          peakLevel: null,
          trackQuality: null,
          copyCrc: null,
          clickCount: null,
          ripLogSource: null,
          qualityCheckedAt: null,
        );
        when(() => mockDao.getTracksForAlbum('rip-1'))
            .thenAnswer((_) async => [row]);

        final tracks = await repository.getTracksForAlbum('rip-1');

        final track = tracks.first;
        expect(track.accurateRipStatus, isNull);
        expect(track.accurateRipConfidence, isNull);
        expect(track.accurateRipCrc, isNull);
        expect(track.peakLevel, isNull);
        expect(track.trackQuality, isNull);
        expect(track.copyCrc, isNull);
        expect(track.clickCount, isNull);
        expect(track.ripLogSource, isNull);
        expect(track.qualityCheckedAt, isNull);
      },
    );

    test(
      'getTracksForAlbum_withNoTracks_returnsEmptyList',
      () async {
        when(() => mockDao.getTracksForAlbum('rip-empty'))
            .thenAnswer((_) async => []);

        final tracks = await repository.getTracksForAlbum('rip-empty');

        expect(tracks, isEmpty);
      },
    );
  });

  // -------------------------------------------------------------------------
  group('insertAlbum', () {
    test(
      'insertAlbum_callsDaoWithCompanionContainingAllEntityFields',
      () async {
        when(() => mockDao.insertAlbum(any())).thenAnswer((_) async {});

        final album = RipAlbum(
          id: 'rip-new',
          libraryPath: 'Pink Floyd/DSOTM',
          artist: 'Pink Floyd',
          albumTitle: 'The Dark Side of the Moon',
          barcode: '5099902895123',
          trackCount: 10,
          discCount: 1,
          totalSizeBytes: 700000000,
          mediaItemId: 'item-99',
          lastScannedAt: 1700000000000,
          updatedAt: 1700000001000,
        );

        await repository.insertAlbum(album);

        final captured = verify(
          () => mockDao.insertAlbum(captureAny()),
        ).captured.single as RipAlbumsTableCompanion;

        expect(captured.id.value, 'rip-new');
        expect(captured.libraryPath.value, 'Pink Floyd/DSOTM');
        expect(captured.artist.value, 'Pink Floyd');
        expect(captured.albumTitle.value, 'The Dark Side of the Moon');
        expect(captured.barcode.value, '5099902895123');
        expect(captured.trackCount.value, 10);
        expect(captured.discCount.value, 1);
        expect(captured.totalSizeBytes.value, 700000000);
        expect(captured.mediaItemId.value, 'item-99');
        expect(captured.lastScannedAt.value, 1700000000000);
        expect(captured.updatedAt.value, 1700000001000);
      },
    );
  });

  // -------------------------------------------------------------------------
  group('insertTracks', () {
    test(
      'insertTracks_buildsCompanionForEachTrackAndDelegatesToDao',
      () async {
        when(() => mockDao.insertTracks(any())).thenAnswer((_) async {});

        final tracks = [
          RipTrack(
            id: 'track-a',
            ripAlbumId: 'rip-1',
            discNumber: 1,
            trackNumber: 1,
            title: 'Alpha',
            filePath: '/music/a.flac',
            durationMs: 200000,
            fileSizeBytes: 40000000,
            updatedAt: 1700000001000,
            accurateRipStatus: 'ok',
            accurateRipConfidence: 10,
            accurateRipCrc: 'CRC1',
            peakLevel: -1.0,
            trackQuality: 99.0,
            copyCrc: 'CCRC1',
            clickCount: 0,
            ripLogSource: 'dBpoweramp',
            qualityCheckedAt: 1700000002000,
          ),
          RipTrack(
            id: 'track-b',
            ripAlbumId: 'rip-1',
            discNumber: 1,
            trackNumber: 2,
            title: 'Beta',
            filePath: '/music/b.flac',
            fileSizeBytes: 35000000,
            updatedAt: 1700000001000,
          ),
        ];

        await repository.insertTracks(tracks);

        final capturedList = verify(
          () => mockDao.insertTracks(captureAny()),
        ).captured.single as List<RipTracksTableCompanion>;

        expect(capturedList, hasLength(2));

        final first = capturedList[0];
        expect(first.id.value, 'track-a');
        expect(first.ripAlbumId.value, 'rip-1');
        expect(first.trackNumber.value, 1);
        expect(first.title.value, 'Alpha');
        expect(first.filePath.value, '/music/a.flac');
        expect(first.durationMs.value, 200000);
        expect(first.fileSizeBytes.value, 40000000);
        expect(first.accurateripStatus.value, 'ok');
        expect(first.accurateripConfidence.value, 10);
        expect(first.accurateripCrc.value, 'CRC1');
        expect(first.peakLevel.value, -1.0);
        expect(first.trackQuality.value, 99.0);
        expect(first.copyCrc.value, 'CCRC1');
        expect(first.clickCount.value, 0);
        expect(first.ripLogSource.value, 'dBpoweramp');
        expect(first.qualityCheckedAt.value, 1700000002000);

        final second = capturedList[1];
        expect(second.id.value, 'track-b');
        expect(second.trackNumber.value, 2);
        expect(second.filePath.value, '/music/b.flac');
      },
    );
  });

  // -------------------------------------------------------------------------
  group('linkToMediaItem', () {
    test(
      'linkToMediaItem_delegatesToDaoWithCorrectIds',
      () async {
        when(() => mockDao.linkToMediaItem(any(), any()))
            .thenAnswer((_) async {});

        await repository.linkToMediaItem('rip-1', 'item-42');

        verify(() => mockDao.linkToMediaItem('rip-1', 'item-42')).called(1);
      },
    );
  });

  // -------------------------------------------------------------------------
  group('unlinkFromMediaItem', () {
    test(
      'unlinkFromMediaItem_delegatesToDaoWithAlbumId',
      () async {
        when(() => mockDao.unlinkFromMediaItem(any()))
            .thenAnswer((_) async {});

        await repository.unlinkFromMediaItem('rip-1');

        verify(() => mockDao.unlinkFromMediaItem('rip-1')).called(1);
      },
    );
  });

  // -------------------------------------------------------------------------
  group('softDeleteAlbum', () {
    test(
      'softDeleteAlbum_callsDaoWithIdAndCurrentEpochTimestamp',
      () async {
        when(() => mockDao.softDeleteAlbum(any(), any()))
            .thenAnswer((_) async {});

        final before = DateTime.now().millisecondsSinceEpoch;
        await repository.softDeleteAlbum('rip-1');
        final after = DateTime.now().millisecondsSinceEpoch;

        final captured = verify(
          () => mockDao.softDeleteAlbum('rip-1', captureAny()),
        ).captured.single as int;

        // The timestamp must be within the window of the call.
        expect(captured, greaterThanOrEqualTo(before));
        expect(captured, lessThanOrEqualTo(after));
      },
    );
  });

  // -------------------------------------------------------------------------
  group('updateTrackQuality', () {
    test(
      'updateTrackQuality_passesAllNamedParametersThroughToDao',
      () async {
        when(
          () => mockDao.updateTrackQuality(
            any(),
            arStatus: any(named: 'arStatus'),
            arConfidence: any(named: 'arConfidence'),
            arCrc: any(named: 'arCrc'),
            peakLevel: any(named: 'peakLevel'),
            trackQuality: any(named: 'trackQuality'),
            copyCrc: any(named: 'copyCrc'),
            clickCount: any(named: 'clickCount'),
            ripLogSource: any(named: 'ripLogSource'),
            qualityCheckedAt: any(named: 'qualityCheckedAt'),
          ),
        ).thenAnswer((_) async {});

        await repository.updateTrackQuality(
          'track-7',
          arStatus: 'verified',
          arConfidence: 5,
          arCrc: 'DEADBEEF',
          peakLevel: -0.1,
          trackQuality: 97.3,
          copyCrc: 'CAFEBABE',
          clickCount: 2,
          ripLogSource: 'EAC',
          qualityCheckedAt: 1700000005000,
        );

        verify(
          () => mockDao.updateTrackQuality(
            'track-7',
            arStatus: 'verified',
            arConfidence: 5,
            arCrc: 'DEADBEEF',
            peakLevel: -0.1,
            trackQuality: 97.3,
            copyCrc: 'CAFEBABE',
            clickCount: 2,
            ripLogSource: 'EAC',
            qualityCheckedAt: 1700000005000,
          ),
        ).called(1);
      },
    );

    test(
      'updateTrackQuality_withAllNullOptionals_delegatesNullsThroughToDao',
      () async {
        when(
          () => mockDao.updateTrackQuality(
            any(),
            arStatus: any(named: 'arStatus'),
            arConfidence: any(named: 'arConfidence'),
            arCrc: any(named: 'arCrc'),
            peakLevel: any(named: 'peakLevel'),
            trackQuality: any(named: 'trackQuality'),
            copyCrc: any(named: 'copyCrc'),
            clickCount: any(named: 'clickCount'),
            ripLogSource: any(named: 'ripLogSource'),
            qualityCheckedAt: any(named: 'qualityCheckedAt'),
          ),
        ).thenAnswer((_) async {});

        await repository.updateTrackQuality('track-8');

        verify(
          () => mockDao.updateTrackQuality(
            'track-8',
            arStatus: null,
            arConfidence: null,
            arCrc: null,
            peakLevel: null,
            trackQuality: null,
            copyCrc: null,
            clickCount: null,
            ripLogSource: null,
            qualityCheckedAt: null,
          ),
        ).called(1);
      },
    );
  });
}
