#!/usr/bin/env bash
#
# Run or build MyMediaScanner on an iOS Simulator.
#
# Google ML Kit (google_mlkit_text_recognition) ships no arm64-simulator
# binary, so Flutter builds the simulator app as x86_64 — which cannot run on
# Apple-Silicon iOS 26+ simulators. This script temporarily swaps the plugin
# for a pure-Dart no-op stub (via pubspec_overrides.yaml) so the simulator
# build links as arm64. Cover OCR returns no text on the simulator; barcode
# scanning and the rest of the app are unaffected.
#
# Real devices: just run `flutter run` / `flutter build ios` normally — the
# genuine ML Kit plugin is used and OCR works fully.
#
# Usage:
#   scripts/ios_sim.sh                 # flutter run on the first iOS simulator
#   scripts/ios_sim.sh -d "iPhone 17"  # target a specific simulator
#   scripts/ios_sim.sh build           # flutter build ios --simulator
set -euo pipefail

cd "$(dirname "$0")/.."

# CocoaPods does not reliably notice the changed plugin set on its own, so we
# force a clean pod resolve whenever the override is toggled on or off.
clean_pods() {
  rm -rf ios/Pods ios/Podfile.lock
}

restore() {
  rm -f pubspec_overrides.yaml
  flutter pub get >/dev/null 2>&1 || true
  clean_pods
}
trap restore EXIT

cat > pubspec_overrides.yaml <<'YAML'
# AUTO-GENERATED by scripts/ios_sim.sh — do not commit.
# Swaps Google ML Kit for a pure-Dart stub so the iOS simulator builds arm64.
dependency_overrides:
  google_mlkit_text_recognition:
    path: tool/mlkit_text_recognition_stub
YAML

flutter pub get
clean_pods

if [[ "${1:-}" == "build" ]]; then
  shift
  flutter build ios --simulator --debug "$@"
else
  flutter run "$@"
fi
